version: '2'
services:
  logrotate:
    start_on_create: true
  elasticsearch:
    scale: 1
    start_on_create: true
  filebeat:
    start_on_create: true
  kibana:
    scale: 1
    start_on_create: true
